repositories:
  - name: cloudnative-pg
    url: https://cloudnative-pg.io/charts

releases:
  - name: postgresql
    namespace: postgresql
    chart: cloudnative-pg/cloudnative-pg
    createNamespace: true

  - name: postgresql-manifests
    namespace: postgresql
    chart: ./postgresql-manifests
    needs:
      - postgresql